# Generated by Django 2.2.9 on 2020-02-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200226_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
