# Generated by Django 2.2.9 on 2020-02-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200227_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgroup',
            old_name='name',
            new_name='group_name',
        ),
    ]
