# Generated by Django 2.2.9 on 2020-02-26 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20200226_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='eventgroup',
            name='members',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='event_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
