# Generated by Django 2.2.9 on 2020-02-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200227_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgroup',
            old_name='members',
            new_name='attendees',
        ),
    ]
