# Generated by Django 2.2.9 on 2020-02-26 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20200226_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_groups+', to=settings.AUTH_USER_MODEL),
        ),
    ]
