# Generated by Django 2.2.9 on 2020-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_review'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='events',
        ),
        migrations.AddField(
            model_name='sport',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='sports', to='events.Event'),
        ),
    ]
