# Generated by Django 2.2.9 on 2020-03-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200228_1407'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='_user_shopping_cart_+', to='events.Event'),
        ),
    ]
